robot:
  l1: 2.0
  l2: 2.0

env:
  rectangles:
    - [-0.7, 1.3, 2.0, 2.2]
    - [2.0, -2.0, 1.0, 4.0]
    - [-3.0, -3.0, 1.25, 2.0]

qlimit: [6.28318530718, 6.28318530718] # 2 * PI

qstart: [-1.20, 0.0]

# qgoal: [2.16, -0.5]
qgoal: [-4.12319, 5.78319]

range: 0.3
bias: 0.05
time_limit: 2.0
simplify_solution: true

save_planner_data: paper_r2s_snggoal_planner_data
save_start_goal: paper_r2s_snggoal_start_goal
save_path: paper_r2s_snggoal_path
